### ISSUE TITLE
Error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by toanld** [YujiroTakahashi/fastText-php#1]
/home/setup/fastText/fastText-php/fasttext.c: In function ‘zim_fasttext_getWordVectors’:
/home/setup/fastText/fastText-php/fasttext.c:257:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int64_t idx=0; idx<ft_vecs->size; idx++) {
  ^
/home/setup/fastText/fastText-php/fasttext.c:257:2: note: use option -std=c99 or -std=gnu99 to compile your code
/home/setup/fastText/fastText-php/fasttext.c: In function ‘zim_fasttext_getSubwordVector’:
/home/setup/fastText/fastText-php/fasttext.c:282:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int64_t idx=0; idx<ft_vecs->size; idx++) {
  ^
/home/setup/fastText/fastText-php/fasttext.c: In function ‘zim_fasttext_getSentenceVectors’:
/home/setup/fastText/fastText-php/fasttext.c:307:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int64_t idx=0; idx<ft_vecs->size; idx++) {
  ^
/home/setup/fastText/fastText-php/fasttext.c: In function ‘zim_fasttext_getPredict’:
/home/setup/fastText/fastText-php/fasttext.c:339:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int idx=0; idx<ft_vals->size; idx++) {
  ^
/home/setup/fastText/fastText-php/fasttext.c: In function ‘zim_fasttext_getNN’:
/home/setup/fastText/fastText-php/fasttext.c:371:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int idx=0; idx<ft_vals->size; idx++) {
  ^
/home/setup/fastText/fastText-php/fasttext.c: In function ‘zim_fasttext_getAnalogies’:
/home/setup/fastText/fastText-php/fasttext.c:403:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int idx=0; idx<ft_vals->size; idx++) {
  ^
/home/setup/fastText/fastText-php/fasttext.c: In function ‘zim_fasttext_getNgramVectors’:
/home/setup/fastText/fastText-php/fasttext.c:434:2: error: ‘for’ loop initial declarations are only allowed in C99 mode

**Comment by YujiroTakahashi** [comment]
https://github.com/YujiroTakahashi/fastText-php/blob/master/config.m4#L43

**Comment by YujiroTakahashi** [comment]
Changed to json format.

Thank you,
Takahashi
