### ISSUE TITLE
Issue with loading extension & running code

### ISSUE THREAD

**Issue by lobochrome** [YujiroTakahashi/fastText-php#3]
Dear Takahashi-san,

It seems I've run into a similar issue as Issue #2:
I've installed fasttext 0.1.0 using cmake and it's running fine on the command line, alas after following your instructions for installing the php-bindings I still get this error:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/fasttext.so' - libfasttext.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Fatal error:  Uncaught Error: Class 'fastText' not found in /home/aqbanking/fasttext.php:3
Stack trace:
#0 {main}
  thrown in /home/aqbanking/fasttext.php on line 3
```

any ideas?

**Comment by lobochrome** [comment]
I've since got a little further with this issue by adding usr/local/lib to my PATH. now it just fails by outputting 
`php: symbol lookup error: /usr/lib/php/20151012/fasttext.so: undefined symbol: zend_strpprintf`

the code is as follows:
```
<?php
	
	$ftext = new fastText();
	$model = '/home/user/labels.bin';
	$ftext->load($model);
	
	$probs = $ftext->getPredict('amazon');
	foreach ($probs as $row) {
	    echo $row['label'].'  '.$row['prob'];
	}
?>
```

I believe the error happens when I use the getPredict method on the fastText object. If I comment those lines out it runs without error, alas all methods applied to $ftext fail.

**Comment by YujiroTakahashi** [comment]
Hello @lobochrome .

Thank you for your bug report.

Threshold argument was added.

https://github.com/YujiroTakahashi/fastText-php/blob/master/fasttext_api.cc#L228
```c
 fasttext->predict(k, words, predictions, threshold);
```

Thank you,
Takahashi
