### ISSUE TITLE
fastText-php/json.hpp:67:10: error: #error "unsupported GCC version

### ISSUE THREAD

**Issue by KiyoshiHirose** [YujiroTakahashi/fastText-php#4]
Takahashi-san,

fastText was installed without a problem but during make session of fastText-php, I encountered the following error message;

/my-dir/fastText-php/json.hpp:67:10: error: #error "unsupported GCC version - see (URL is omitted)

My GCC version is 4.8.5-36.
What's going on and let me know how to resolve this situation.

Thanks in advance,
Kiyoshi Hirose.

**Comment by YujiroTakahashi** [comment]
@KiyoshiHirose さん

投稿ありがとう御座います。

fastText-phpでは、以下のJSONライブラリを使っています。
https://github.com/nlohmann/json

私の開発環境では、以下のGCCを使っています。
`gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)`


GCCのバージョンを上げられない事情があれば以下のバージョンをご利用下さい。
（結構古いGCCでもコンパイル出来るように修正してくれています）
https://github.com/socialwire/fastText-php

上記バージョンのfastText対応はv0.1.0だったと思います。
https://github.com/facebookresearch/fastText/tree/v0.1.0

以上、よろしくお願いします。

高橋 裕志郎

**Comment by KiyoshiHirose** [comment]
高橋様、

リプライありがとうございました。
頂いた情報を元に再度やってみます。
また結果はここにアップします。

広瀬 潔.
